name: aurora_app
description: "The next generation Concierge."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  cached_network_image: ^3.4.1
  chopper: ^8.4.0
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  chopper_generator: ^8.4.0
  json_serializable: ^6.11.1
  freezed: ^3.2.3
  build_runner: ^2.10.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/